// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PropTradingCommonProtocol.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace PropTradingProtocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PingMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool Connected { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AckValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PongMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool Connected { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AckValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractRequestWrapperMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<ContractReqMsg> Contracts { get; } = new global::System.Collections.Generic.List<ContractReqMsg>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public SymbolCategoryEnum Category { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Isin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractResponseWrapperMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<ContractRespMsg> Contracts { get; } = new global::System.Collections.Generic.List<ContractRespMsg>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public SymbolCategoryEnum Category { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ContractInfoMsg contractInfo { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool IsFinal { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContractInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContractName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Symbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Exchange { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public double TickSize { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double TickValue { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public bool IsStock { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TradableQuantityFractionable { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public double TradableQuantityMultiplier { get; set; }

        [global::ProtoBuf.ProtoMember(14, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(15, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long SymbolId { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string QuoteCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BaseCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TradableQuantityMinimum { get; set; }

        [global::ProtoBuf.ProtoMember(19, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TradableQuantityMultiple { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountTradingSymbolMultiReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<TradingSymbolParamReqMsg> Symbols { get; } = new global::System.Collections.Generic.List<TradingSymbolParamReqMsg>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradingSymbolParamReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountTradingSymbolMultiRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<AccountTradingSymbolInfoMsg> Infos { get; } = new global::System.Collections.Generic.List<AccountTradingSymbolInfoMsg>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountTradingSymbolInfoReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountTradingSymbolInfoRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public AccountTradingSymbolInfoMsg Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountTradingSymbolInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long SymbolId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double Commissions { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double Margin { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Leverage { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public SymbolSpreadTypeEnum SpreadType { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int SpreadTickValue { get; set; }

        [global::ProtoBuf.ProtoMember(8, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TradableQuantityFractionable { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double TradableQuantityMultiplier { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string QuoteCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BaseCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyPlReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyPlRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double DailyPl { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double DailyNetPl { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Isin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        public double ConvertedDailyPl { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double ConvertedDailyNetPl { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InfoReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public InfoModeEnum Mode { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public AccountStatusEnum AccountListFilterStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsPacked = true)]
        public long[] Accounts { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public global::System.Collections.Generic.List<InfoModeEnum> Modes { get; } = new global::System.Collections.Generic.List<InfoModeEnum>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InfoRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"AccountList")]
        public global::System.Collections.Generic.List<AccountHeaderMsg> AccountLists { get; } = new global::System.Collections.Generic.List<AccountHeaderMsg>();

        [global::ProtoBuf.ProtoMember(2, Name = @"OrderList")]
        public global::System.Collections.Generic.List<OrderInfoMsg> OrderLists { get; } = new global::System.Collections.Generic.List<OrderInfoMsg>();

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"PositionList")]
        public global::System.Collections.Generic.List<PositionInfoMsg> PositionLists { get; } = new global::System.Collections.Generic.List<PositionInfoMsg>();

        [global::ProtoBuf.ProtoMember(5, Name = @"BracketList")]
        public global::System.Collections.Generic.List<BracketInfoMsg> BracketLists { get; } = new global::System.Collections.Generic.List<BracketInfoMsg>();

        [global::ProtoBuf.ProtoMember(6, Name = @"AccountTradingSymbolList")]
        public global::System.Collections.Generic.List<AccountTradingSymbolInfoMsg> AccountTradingSymbolLists { get; } = new global::System.Collections.Generic.List<AccountTradingSymbolInfoMsg>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountHeaderMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long accountNumber { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string accountHeader { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string accountDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public BalanceMsg Balance { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool IsEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public AccountStatusEnum Status { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool IsTradingEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool IsHedging { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountReferenceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public AccountPermissionEnum Permission { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Currency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        public bool Archived { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public bool UserRiskRuleEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public bool UserDailyLockoutEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public bool IsTradeCopierAllowed { get; set; }

        [global::ProtoBuf.ProtoMember(16, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrganizationId { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string OrganizationName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18)]
        public AccountModeEnum Mode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountSubscribeReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsPacked = true)]
        public long[] Accounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountSubscribeRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public OrderInsertMsg OrderInsert { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public OrderRemoveMsg OrderRemove { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public OrderModifyMsg OrderModify { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public BracketStrageyInsertMsg BracketStrategyInsert { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public BracketModifyMsg BracketModify { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public OcoGroupCreateMsg OcoGroupCreate { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public OcoGroupRemoveMsg OcoGroupRemove { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public PositionFlatMsg PositionFlatMsg { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public BracketInsertMsg BracketInsert { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public BracketRemoveMsg BracketRemove { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderInsertMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int SeqClientId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double Price { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public OrderTypeEnum OrderType { get; set; }

        [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double LimitPrice { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public BracketStrategyParam BracketStrategy { get; set; }

        [global::ProtoBuf.ProtoMember(9, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RefPositionId { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public RequestSourceEnum Source { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public OrderQuantityModeEnum QuantityMode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderModifyMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrgServerId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int NewSeqClientId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double Price { get; set; }

        [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double LimitPrice { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderRemoveMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrgServerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketStrategyParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public TypeEnum Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<BracketParam> Stops { get; } = new global::System.Collections.Generic.List<BracketParam>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<BracketParam> Targets { get; } = new global::System.Collections.Generic.List<BracketParam>();

        [global::ProtoBuf.ProtoMember(4)]
        public StopTrailingModeEnum TrailingMode { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int TrailingTicks { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int TrailingMinOffsetTicks { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TypeEnum
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STOP_AND_TARGET")]
            StopAndTarget = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"STOP_AND_TARGET_STATIC")]
            StopAndTargetStatic = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"STOP")]
            Stop = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"STOP_STATIC")]
            StopStatic = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TARGET")]
            Target = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TARGET_STATIC")]
            TargetStatic = 5,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum StopTrailingModeEnum
        {
            None = 0,
            Breakeven = 1,
            Trailing = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PriceModeEnum PriceMode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int TicksOffset { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double Price { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum PriceModeEnum
        {
            Ticks = 0,
            Price = 1,
            PriceOffset = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketStrageyInsertMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ParentOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BracketStrategyParam BracketStrategy { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public RequestSourceEnum Source { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool IsReplace { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketInsertMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ParentOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool IsTarget { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public BracketParam BracketParam { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int ClientId { get; set; }

        [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketModifyMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ParentOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long BracketId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BracketParam BracketParam { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int ClientId { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketRemoveMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ParentOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long BracketId { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OcoGroupCreateMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public GroupTypeEnum Type { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsPacked = true)]
        public long[] OcoLinkedOrderIds { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public OcoOrdersPlaceEnum OrderPlace { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"OrderInsert")]
        public global::System.Collections.Generic.List<OrderInsertMsg> OrderInserts { get; } = new global::System.Collections.Generic.List<OrderInsertMsg>();

        [global::ProtoBuf.ProtoMember(7)]
        public RequestSourceEnum Source { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GroupTypeEnum
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STOPS_LIMITS")]
            StopsLimits = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"OPPOSITE_QTY")]
            OppositeQty = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum OcoOrdersPlaceEnum
        {
            [global::ProtoBuf.ProtoEnum(Name = @"EXISTING")]
            Existing = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"INSERT")]
            Insert = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OcoGroupRemoveMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OcoGroupId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OcoGroupReportMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OcoGroupId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PositionFlatMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long PositionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RequestSourceEnum Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OrderInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrgServerId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int OrgClientId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long SeqServerId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int SeqClientId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double OrderPrice { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double OrderLimitPrice { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int PendingQty { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int FilledQty { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public OrderTypeEnum OrderType { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public OrderStateEnum OrderState { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public double AvgPrice { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public SnapTypeEnum SnapType { get; set; }

        [global::ProtoBuf.ProtoMember(14, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Isin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OcoLinkedGroupId { get; set; }

        [global::ProtoBuf.ProtoMember(19, DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsPacked = true)]
        public long[] OcoLinkedOrderIds { get; set; }

        [global::ProtoBuf.ProtoMember(20, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OcoParentOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(21, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long PositionLinkId { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public bool IsGeneratedFromBracket { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public OrderQuantityModeEnum QuantityMode { get; set; }

        [global::ProtoBuf.ProtoMember(24, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long InsertUtc { get; set; }

        [global::ProtoBuf.ProtoMember(25, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ExeuctionUtc { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(27)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source { get; set; } = "";

        [global::ProtoBuf.ProtoMember(100, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrgClientSessionId { get; set; }

        [global::ProtoBuf.ProtoMember(101, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long SeqClientSessionId { get; set; }

        [global::ProtoBuf.ProtoMember(102)]
        public bool IsValidationError { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum OrderStateEnum
        {
            Submitted = 0,
            Canceled = 1,
            Error = 2,
            ErrorModify = 3,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum SnapTypeEnum
        {
            Historical = 1,
            RealTime = 2,
            HistPos = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ParentOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OcoGroupId { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long BracketId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int SeqClientId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double Price { get; set; }

        [global::ProtoBuf.ProtoMember(7, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Ticks { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double CalculatedPrice { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int TotalQty { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int ReleasedQty { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public bool IsTarget { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public BracketStateEnum BracketState { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public SnapTypeEnum SnapType { get; set; }

        [global::ProtoBuf.ProtoMember(14, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Isin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(101, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ClientSessionId { get; set; }

        [global::ProtoBuf.ProtoMember(102)]
        public bool IsValidationError { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum BracketStateEnum
        {
            Waiting = 0,
            Submitted = 1,
            Cancelled = 2,
            Error = 3,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum SnapTypeEnum
        {
            Historical = 1,
            RealTime = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PositionInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OpenQuantity { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double OpenPrice { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double MarginUsed { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long DailyBought { get; set; }

        [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long DailySold { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double DailyPl { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool HasOpenPl { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double OpenPl { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double DailyCommissions { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public SnapTypeEnum SnapType { get; set; }

        [global::ProtoBuf.ProtoMember(12, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Isin { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long PositionId { get; set; }

        [global::ProtoBuf.ProtoMember(16, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Utc { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public double ConvertedDailyPl { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public double ConvertedDailyCommissions { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public double ConvertedOpenPl { get; set; }

        [global::ProtoBuf.ProtoMember(20, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long EntryOrderId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum SnapTypeEnum
        {
            Historical = 1,
            RealTime = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BalanceMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public double Balance { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public double MarginUsed { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double StopDrawdownOverall { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double StopDrawdownIntraday { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double ProfitTarget { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double MarginAvailable { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double StopDrawdownWeekly { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double Equity { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double DailyPl { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public double DailyNetPl { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public BalanceDetailedMsg Details { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BalanceDetailedMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool Empty { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public double StopDrawdownOverallValue { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double StopDrawdownIntradayValue { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public double ProfitTargetValue { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double StopDrawdownWeeklyValue { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double UserDrawdownDailyBalance { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public double UserDrawdownWeeklyBalance { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double UserProfitDailyBalance { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double UserProfitWeeklyBalance { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double UserDrawdownDailyValue { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double UserDrawdownWeeklyValue { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public double UserProfitDailyValue { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public double UserProfitWeeklyValue { get; set; }

        [global::ProtoBuf.ProtoMember(14, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int SessionsNumber { get; set; }

        [global::ProtoBuf.ProtoMember(15, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int SessionsNumberTarget { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public double StartBalance { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SymbolLookupReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Filter { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SymbolLookupRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SymbolLookupInfo> Symbols { get; } = new global::System.Collections.Generic.List<SymbolLookupInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SymbolLookupInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Symbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Exchange { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public double TickSize { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public double OrderCommission { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public SymbolCategoryEnum Category { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string DataFeedProduct { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool TradingInhibited { get; set; }

        [global::ProtoBuf.ProtoMember(10, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TradableQuantityFractionable { get; set; }

        [global::ProtoBuf.ProtoMember(11, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TradableQuantityMinimum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelFlatReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ContractsId", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsPacked = true)]
        public long[] ContractsIds { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ActionEnum Action { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public RequestSourceEnum Source { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public OrderPositionFilterEnum Filter { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool CancelExcludeOco { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ActionEnum
        {
            [global::ProtoBuf.ProtoEnum(Name = @"FLAT")]
            Flat = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CANCEL")]
            Cancel = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FLAT_CANCEL")]
            FlatCancel = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelFlatRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<CancelFlatErrorDetail> Errors { get; } = new global::System.Collections.Generic.List<CancelFlatErrorDetail>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<CancelFlatItemDetail> Items { get; } = new global::System.Collections.Generic.List<CancelFlatItemDetail>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelFlatItemDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool IsPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long PositionId { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrderId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelFlatErrorDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelReverseReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ActionEnum Action { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public RequestSourceEnum Source { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ActionEnum
        {
            [global::ProtoBuf.ProtoEnum(Name = @"REVERSE")]
            Reverse = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CANCEL")]
            Cancel = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"REVERSE_CANCEL")]
            ReverseCancel = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelReverseRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BracketInsertReportMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountStatusUpdateMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public EntityActionEnum Action { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public AccountHeaderMsg Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FillReportMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long FillId { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Utc { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public double Price { get; set; }

        [global::ProtoBuf.ProtoMember(7, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double Commissions { get; set; }

        [global::ProtoBuf.ProtoMember(9, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long SourceOrderId { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string SourceOrderIp { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TradeReportMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long TradeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long EntryUtc { get; set; }

        [global::ProtoBuf.ProtoMember(7, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ExitUtc { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public double OpenPrice { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public double ClosePrice { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double GrossPL { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double Commissions { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public bool Unaccounted { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsPacked = true)]
        public global::System.Collections.Generic.List<Flag> Flags { get; } = new global::System.Collections.Generic.List<Flag>();

        [global::ProtoBuf.ProtoContract()]
        public enum Flag
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SCALP")]
            Scalp = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CLOSED_TOO_CLOSE_TO_ENTRY")]
            ClosedTooCloseToEntry = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TRADING_NEWS")]
            TradingNews = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FillTradeReportMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public FillTradeTypeEnum FillType { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long PositionId { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long OrderId { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ContractId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedSymbol { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(8, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long EntryUtc { get; set; }

        [global::ProtoBuf.ProtoMember(9, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ExitUtc { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double OpenPrice { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double ClosePrice { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public double ConvertedGrossPL { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public double ConvertedCommissions { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum FillTradeTypeEnum
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OPEN")]
            Open = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CLOSE")]
            Close = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserSessionLogMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long StartUtc { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long EndUtc { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long ClientSessionId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CurrencyRatesReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public SubscribeModeEnum Mode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CurrencyRateInfoMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BaseCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string QuoteCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public double Rate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountUserRiskRule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool IsScheduled { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool SetAsDefaultForAccountTradingRule { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool InhibitChangesUntilNextSession { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool DailyLossLimitEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public RiskUserLossModeEnum DailyLossLimitMode { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public double DailyLossLimitValue { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public double DailyLossLimitPercentage { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public bool DailyProfitLimitEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public RiskUserTargetModeEnum DailyProfitLimitMode { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public double DailyProfitLimitValue { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public double DailyProfitLimitPercentage { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public bool WeeklyLossLimitEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public RiskUserLossModeEnum WeeklyLossLimitMode { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public double WeeklyLossLimitValue { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public double WeeklyLossLimitPercentage { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public bool WeeklyProfitLimitEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public RiskUserTargetModeEnum WeeklyProfitLimitMode { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public double WeeklyProfitLimitValue { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public double WeeklyProfitLimitPercentage { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountUserRiskRuleInfoReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountUserRiskRuleInfoRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public AccountUserRiskRule Rule { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountUserRiskRuleSetReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public AccountUserRiskRule Rule { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountUserRiskRuleSetRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<string> Errors { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountDailyLockoutReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long AccountId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountDailyLockoutRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountHistoricalSessionReqMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsPacked = true)]
        public long[] AccountIds { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public AccountHistoricalEntityEnum Entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountHistoricalSessionRespMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<FillReportMsg> Fills { get; } = new global::System.Collections.Generic.List<FillReportMsg>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<TradeReportMsg> Trades { get; } = new global::System.Collections.Generic.List<TradeReportMsg>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<OrderInfoMsg> Orders { get; } = new global::System.Collections.Generic.List<OrderInfoMsg>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<FillTradeReportMsg> FillTrades { get; } = new global::System.Collections.Generic.List<FillTradeReportMsg>();

        [global::ProtoBuf.ProtoMember(6)]
        public bool IsPartial { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SymbolCategoryEnum
    {
        Future = 1,
        Forex = 2,
        Index = 3,
        Option = 4,
        Stock = 5,
        CryptoPerpetual = 6,
        Spot = 7,
        Etf = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SymbolSpreadTypeEnum
    {
        Native = 0,
        BidDifference = 1,
        AskDifference = 2,
        PercentualSpread = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum InfoModeEnum
    {
        Account = 1,
        OrdAndPos = 2,
        Positions = 3,
        AccountTradingSymbols = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountModeEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EVALUATION")]
        Evaluation = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SIM_FUNDED")]
        SimFunded = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNDED")]
        Funded = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LIVE")]
        Live = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL")]
        Trial = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"CONTEST")]
        Contest = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAINING")]
        Training = 100,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountStatusEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALL")]
        All = -1,
        [global::ProtoBuf.ProtoEnum(Name = @"INITIALIZED")]
        Initialized = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ENABLED")]
        Enabled = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
        Failed = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DISABLED")]
        Disabled = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountPermissionEnum
    {
        Trading = 0,
        ReadOnly = 1,
        RiskPause = 2,
        LiquidateOnly = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OrderTypeEnum
    {
        Market = 0,
        Limit = 1,
        Stop = 2,
        StopLimit = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OrderExpireEnum
    {
        Never = 1,
        TillDay = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RequestSourceEnum
    {
        Unknown = 0,
        Manual = 1,
        Automatic = 2,
        Copy = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OrderQuantityModeEnum
    {
        Fixed = 0,
        All = 1,
        AccountCountervalue = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OrderPositionFilterEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALL")]
        All = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BUY")]
        Buy = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SELL")]
        Sell = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"WINNER")]
        Winner = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LOOSER")]
        Looser = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EntityActionEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SNAPSHOT")]
        Snapshot = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
        Add = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE")]
        Update = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"REMOVE")]
        Remove = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SubscribeModeEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SNAPSHOT")]
        Snapshot = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIBE")]
        Subscribe = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UNSUBSCRIBE")]
        Unsubscribe = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LoginReasonsCodeEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CREDENTIALS")]
        Credentials = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CONCURRENT_SESSION")]
        ConcurrentSession = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UNEXPECTED_ERROR")]
        UnexpectedError = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RiskUserLossModeEnum
    {
        TrailingMaxBalance = 0,
        StaticStartBalance = 1,
        TrailingMaxEquity = 2,
        StaticStartEquity = 3,
        StaticMininmumStartEquityBalance = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RiskUserTargetModeEnum
    {
        Balance = 0,
        Equity = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountHistoricalEntityEnum
    {
        All = 0,
        Orders = 1,
        Trades = 2,
        Fills = 3,
        FillTrades = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
