// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PropTradingProtocol.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace PropTradingProtocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientRequestMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LoginRequestMsg LoginReq { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PingMsg Ping { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public InfoReqMsg InfoReq { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ContractReqMsg ContractReq { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<DailyPlReqMsg> DailyPls { get; } = new global::System.Collections.Generic.List<DailyPlReqMsg>();

        [global::ProtoBuf.ProtoMember(6, Name = @"Order")]
        public global::System.Collections.Generic.List<OrderMsg> Orders { get; } = new global::System.Collections.Generic.List<OrderMsg>();

        [global::ProtoBuf.ProtoMember(7)]
        public LogInfoMsg LogMsg { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public SymbolLookupReqMsg SymbolLookup { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public CancelFlatReqMsg CancelFlatReq { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public AccountSubscribeReqMsg AccountSubscribeReq { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public CancelReverseReqMsg CancelReverseReq { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public CurrencyRatesReqMsg CurrenyRatesReq { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public AccountTradingSymbolInfoReqMsg AccountTradingSymbolInfoReq { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public AccountUserRiskRuleInfoReqMsg AccountUserRiskRuleInfoReq { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public AccountUserRiskRuleSetReqMsg AccountUserRiskRuleSetReq { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public AccountDailyLockoutReqMsg AccountDailyLockoutReq { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public AccountHistoricalSessionReqMsg AccountHistoricalSessionReq { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public ContractRequestWrapperMsg ContractsReqs { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public AccountTradingSymbolMultiReqMsg AccountTradingSymbolMultiReq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerResponseMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LoginResponseMsg LoginMsg { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PongMsg Pong { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public InfoRespMsg InfoMsg { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"BalanceInfo")]
        public global::System.Collections.Generic.List<BalanceMsg> BalanceInfoes { get; } = new global::System.Collections.Generic.List<BalanceMsg>();

        [global::ProtoBuf.ProtoMember(5)]
        public ContractRespMsg ContractMsg { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<DailyPlRespMsg> DailyPls { get; } = new global::System.Collections.Generic.List<DailyPlRespMsg>();

        [global::ProtoBuf.ProtoMember(7, Name = @"OrderInfo")]
        public global::System.Collections.Generic.List<OrderInfoMsg> OrderInfoes { get; } = new global::System.Collections.Generic.List<OrderInfoMsg>();

        [global::ProtoBuf.ProtoMember(8)]
        public LoggedOffMsg LoggedOff { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public LogInfoMsg LogMsg { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public SymbolLookupRespMsg SymbolLookup { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"PositionInfo")]
        public global::System.Collections.Generic.List<PositionInfoMsg> PositionInfoes { get; } = new global::System.Collections.Generic.List<PositionInfoMsg>();

        [global::ProtoBuf.ProtoMember(12)]
        public CancelFlatRespMsg CancelFlatMsg { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"BracketInfo")]
        public global::System.Collections.Generic.List<BracketInfoMsg> BracketInfoes { get; } = new global::System.Collections.Generic.List<BracketInfoMsg>();

        [global::ProtoBuf.ProtoMember(14)]
        public BracketInsertReportMsg BracketStrategyInsertReport { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public AccountSubscribeRespMsg AccountSubscribeResp { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public global::System.Collections.Generic.List<AccountStatusUpdateMsg> AccountStatusUpdates { get; } = new global::System.Collections.Generic.List<AccountStatusUpdateMsg>();

        [global::ProtoBuf.ProtoMember(17)]
        public OcoGroupReportMsg OcoGroupReport { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public global::System.Collections.Generic.List<FillReportMsg> FillReports { get; } = new global::System.Collections.Generic.List<FillReportMsg>();

        [global::ProtoBuf.ProtoMember(19)]
        public global::System.Collections.Generic.List<TradeReportMsg> TradeReports { get; } = new global::System.Collections.Generic.List<TradeReportMsg>();

        [global::ProtoBuf.ProtoMember(20)]
        public global::System.Collections.Generic.List<FillTradeReportMsg> FillTradeReports { get; } = new global::System.Collections.Generic.List<FillTradeReportMsg>();

        [global::ProtoBuf.ProtoMember(21)]
        public CancelReverseRespMsg CancelReverseMsg { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public global::System.Collections.Generic.List<UserSessionLogMsg> UserSessionLogs { get; } = new global::System.Collections.Generic.List<UserSessionLogMsg>();

        [global::ProtoBuf.ProtoMember(23, Name = @"AccountTradingSymbolInfoUpdate")]
        public global::System.Collections.Generic.List<AccountTradingSymbolInfoMsg> AccountTradingSymbolInfoUpdates { get; } = new global::System.Collections.Generic.List<AccountTradingSymbolInfoMsg>();

        [global::ProtoBuf.ProtoMember(24)]
        public global::System.Collections.Generic.List<CurrencyRateInfoMsg> CurrencyRates { get; } = new global::System.Collections.Generic.List<CurrencyRateInfoMsg>();

        [global::ProtoBuf.ProtoMember(25)]
        public AccountTradingSymbolInfoRespMsg AccountTradingSymbolInfoResp { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public AccountUserRiskRuleInfoRespMsg AccountUserRiskRuleInfoResp { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public AccountUserRiskRuleSetRespMsg AccountUserRiskRuleSetResp { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public AccountDailyLockoutRespMsg AccountDailyLockoutResp { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public AccountHistoricalSessionRespMsg AccountHistoricalSessionResp { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public ContractResponseWrapperMsg ContractsResps { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public AccountTradingSymbolMultiRespMsg AccountTradingSymbolMultiResp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRequestMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string OtpCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public bool IsManualAccountSubscribe { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool KeepConcurrentSessionOn { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public AccountSubscriptionModeEnum AccountSubscriptionMode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResponseMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public LoginReasonsCodeEnum ReasonCode { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoggedOffMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountSubscriptionModeEnum
    {
        Undefined = 0,
        Manual = 1,
        Existing = 2,
        ExistingAndNew = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
